#!/bin/sh
#
# @name Coaxial 8-Arm 16-Motor Air Taxi
# @type Multirotor
# @class Octocopter
#

. etc/init.d/rc.mc_defaults

# ============================================================
# 1. INITIALIZE CONTROL ALLOCATOR
# ============================================================
# Stop any running instance to reset the matrix
control_allocator stop

# Set the rotor count first (Critical for unlocking slots 13-16)
param set CA_ROTOR_COUNT 16
param set CA_AIRFRAME 0

# ============================================================
# 2. MOTOR FUNCTION MAPPING (Output 1-16)
# ============================================================
# Map PWM channels to Motor functions (101=Motor1, 116=Motor16)
param set PWM_MAIN_FUNC1 101
param set PWM_MAIN_FUNC2 102
param set PWM_MAIN_FUNC3 103
param set PWM_MAIN_FUNC4 104
param set PWM_MAIN_FUNC5 105
param set PWM_MAIN_FUNC6 106
param set PWM_MAIN_FUNC7 107
param set PWM_MAIN_FUNC8 108
param set PWM_MAIN_FUNC9 109
param set PWM_MAIN_FUNC10 110
param set PWM_MAIN_FUNC11 111
param set PWM_MAIN_FUNC12 112
param set PWM_MAIN_FUNC13 113
param set PWM_MAIN_FUNC14 114
param set PWM_MAIN_FUNC15 115
param set PWM_MAIN_FUNC16 116

# ============================================================
# 3. GEOMETRY (Hardcoded to ensure script reliability)
# ============================================================
# KM 0.05 = CCW, KM -0.05 = CW

# TOP ROTORS (0-7)
param set CA_ROTOR0_PX 0.400;  param set CA_ROTOR0_PY 0.000;  param set CA_ROTOR0_KM 0.05
param set CA_ROTOR1_PX 0.283;  param set CA_ROTOR1_PY 0.283;  param set CA_ROTOR1_KM -0.05
param set CA_ROTOR2_PX 0.000;  param set CA_ROTOR2_PY 0.400;  param set CA_ROTOR2_KM 0.05
param set CA_ROTOR3_PX -0.283; param set CA_ROTOR3_PY 0.283;  param set CA_ROTOR3_KM -0.05
param set CA_ROTOR4_PX -0.400; param set CA_ROTOR4_PY 0.000;  param set CA_ROTOR4_KM 0.05
param set CA_ROTOR5_PX -0.283; param set CA_ROTOR5_PY -0.283; param set CA_ROTOR5_KM -0.05
param set CA_ROTOR6_PX 0.000;  param set CA_ROTOR6_PY -0.400; param set CA_ROTOR6_KM 0.05
param set CA_ROTOR7_PX 0.283;  param set CA_ROTOR7_PY -0.283; param set CA_ROTOR7_KM -0.05

# BOTTOM ROTORS (8-15)
param set CA_ROTOR8_PX 0.400;  param set CA_ROTOR8_PY 0.000;  param set CA_ROTOR8_KM -0.05
param set CA_ROTOR9_PX 0.283;  param set CA_ROTOR9_PY 0.283;  param set CA_ROTOR9_KM 0.05
param set CA_ROTOR10_PX 0.000;  param set CA_ROTOR10_PY 0.400;  param set CA_ROTOR10_KM -0.05
param set CA_ROTOR11_PX -0.283; param set CA_ROTOR11_PY 0.283;  param set CA_ROTOR11_KM 0.05
param set CA_ROTOR12_PX -0.400; param set CA_ROTOR12_PY 0.000;  param set CA_ROTOR12_KM -0.05
param set CA_ROTOR13_PX -0.283; param set CA_ROTOR13_PY -0.283; param set CA_ROTOR13_KM 0.05
param set CA_ROTOR14_PX 0.000;  param set CA_ROTOR14_PY -0.400; param set CA_ROTOR14_KM -0.05
param set CA_ROTOR15_PX 0.283;  param set CA_ROTOR15_PY -0.283; param set CA_ROTOR15_KM 0.05

# ============================================================
# 4. TUNING & BOOT
# ============================================================
param set-default THR_MDL_FAC 0.3
set MAV_TYPE 2

# Final Start - This will now build the 16-channel matrix
control_allocator start
